- name: Load Red Hat credentials
  include_vars:
    file: 'redhat_credentials.yml'

- name: Login to Red Hat registry
  containers.podman.podman_login:
    username: '{{ redhat_username }}'
    password: '{{ redhat_password }}'
    registry: registry.redhat.io

- name: Logout of Red Hat registry
  containers.podman.podman_logout:
    registry: registry.redhat.io