- name: Create Lab job template
  awx.awx.job_template:
    name: "{{ jt_name }}"
    job_type: "{{ jt_type }}"
    organization: "{{ organization }}"
    inventory: "{{ inv_name }}"
    project: "{{ prj_name }}"
    playbook: "{{ jt_playbook }}"
    credential: "{{ jt_credential }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: no
    state: "present"